# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x07raftapp\":\n\x08LogEntry\x12\x11\n\toperation\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\r\n\x05index\x18\x03 \x01(\x05\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"J\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\x12\x0f\n\x07node_id\x18\x03 \x01(\t\"\xa1\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12\"\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x11.raftapp.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\"G\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07node_id\x18\x03 \x01(\t\"5\n\rClientRequest\x12\x11\n\toperation\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\"D\n\x0e\x43lientResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t2\xeb\x01\n\x0bRaftService\x12H\n\x0bRequestVote\x12\x1b.raftapp.RequestVoteRequest\x1a\x1c.raftapp.RequestVoteResponse\x12N\n\rAppendEntries\x12\x1d.raftapp.AppendEntriesRequest\x1a\x1e.raftapp.AppendEntriesResponse\x12\x42\n\x0fSubmitOperation\x12\x16.raftapp.ClientRequest\x1a\x17.raftapp.ClientResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGENTRY._serialized_start=23
  _LOGENTRY._serialized_end=81
  _REQUESTVOTEREQUEST._serialized_start=83
  _REQUESTVOTEREQUEST._serialized_end=186
  _REQUESTVOTERESPONSE._serialized_start=188
  _REQUESTVOTERESPONSE._serialized_end=262
  _APPENDENTRIESREQUEST._serialized_start=265
  _APPENDENTRIESREQUEST._serialized_end=426
  _APPENDENTRIESRESPONSE._serialized_start=428
  _APPENDENTRIESRESPONSE._serialized_end=499
  _CLIENTREQUEST._serialized_start=501
  _CLIENTREQUEST._serialized_end=554
  _CLIENTRESPONSE._serialized_start=556
  _CLIENTRESPONSE._serialized_end=624
  _RAFTSERVICE._serialized_start=627
  _RAFTSERVICE._serialized_end=862
# @@protoc_insertion_point(module_scope)
