version: "3.9"

services:
  fishing1:
    build: .
    environment:
      - NODE_ID=1
      - FISHING_PORT=50051
      - IMAGE_FILE=1.JPG
      - NODE_IPS=fishing1,fishing2,fishing3,fishing4,fishing5
    ports:
      - "50051:50051"
    restart: unless-stopped

  fishing2:
    build: .
    environment:
      - NODE_ID=2
      - FISHING_PORT=50051
      - IMAGE_FILE=2.JPG
      - NODE_IPS=fishing1,fishing2,fishing3,fishing4,fishing5
    ports:
      - "50052:50051"
    restart: unless-stopped

  fishing3:
    build: .
    environment:
      - NODE_ID=3
      - FISHING_PORT=50051
      - IMAGE_FILE=3.JPG
      - NODE_IPS=fishing1,fishing2,fishing3,fishing4,fishing5
    ports:
      - "50053:50051"
    restart: unless-stopped

  fishing4:
    build: .
    environment:
      - NODE_ID=4
      - FISHING_PORT=50051
      - IMAGE_FILE=4.JPG
      - NODE_IPS=fishing1,fishing2,fishing3,fishing4,fishing5
    ports:
      - "50054:50051"
    restart: unless-stopped

  fishing5:
    build: .
    environment:
      - NODE_ID=5
      - FISHING_PORT=50051
      - IMAGE_FILE=5.JPG
      - NODE_IPS=fishing1,fishing2,fishing3,fishing4,fishing5
    ports:
      - "50055:50051"
    restart: unless-stopped
