# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fishing_pb2 as fishing__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fishing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FishingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_stream(
                '/fishingapp.FishingService/ListUsers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=fishing__pb2.User.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/fishingapp.FishingService/Login',
                request_serializer=fishing__pb2.LoginRequest.SerializeToString,
                response_deserializer=fishing__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.UpdateLocation = channel.stream_unary(
                '/fishingapp.FishingService/UpdateLocation',
                request_serializer=fishing__pb2.UpdateLocationRequest.SerializeToString,
                response_deserializer=fishing__pb2.UpdateLocationResponse.FromString,
                _registered_method=True)
        self.StartFishing = channel.unary_stream(
                '/fishingapp.FishingService/StartFishing',
                request_serializer=fishing__pb2.StartFishingRequest.SerializeToString,
                response_deserializer=fishing__pb2.Fish.FromString,
                _registered_method=True)
        self.CurrentUsers = channel.unary_stream(
                '/fishingapp.FishingService/CurrentUsers',
                request_serializer=fishing__pb2.EmptyRequest.SerializeToString,
                response_deserializer=fishing__pb2.CurrentUsersResponse.FromString,
                _registered_method=True)
        self.Inventory = channel.unary_unary(
                '/fishingapp.FishingService/Inventory',
                request_serializer=fishing__pb2.InventoryRequest.SerializeToString,
                response_deserializer=fishing__pb2.InventoryResponse.FromString,
                _registered_method=True)
        self.GetImage = channel.unary_unary(
                '/fishingapp.FishingService/GetImage',
                request_serializer=fishing__pb2.ImageRequest.SerializeToString,
                response_deserializer=fishing__pb2.ImageResponse.FromString,
                _registered_method=True)


class FishingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLocation(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartFishing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CurrentUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inventory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FishingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUsers': grpc.unary_stream_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=fishing__pb2.User.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=fishing__pb2.LoginRequest.FromString,
                    response_serializer=fishing__pb2.LoginResponse.SerializeToString,
            ),
            'UpdateLocation': grpc.stream_unary_rpc_method_handler(
                    servicer.UpdateLocation,
                    request_deserializer=fishing__pb2.UpdateLocationRequest.FromString,
                    response_serializer=fishing__pb2.UpdateLocationResponse.SerializeToString,
            ),
            'StartFishing': grpc.unary_stream_rpc_method_handler(
                    servicer.StartFishing,
                    request_deserializer=fishing__pb2.StartFishingRequest.FromString,
                    response_serializer=fishing__pb2.Fish.SerializeToString,
            ),
            'CurrentUsers': grpc.unary_stream_rpc_method_handler(
                    servicer.CurrentUsers,
                    request_deserializer=fishing__pb2.EmptyRequest.FromString,
                    response_serializer=fishing__pb2.CurrentUsersResponse.SerializeToString,
            ),
            'Inventory': grpc.unary_unary_rpc_method_handler(
                    servicer.Inventory,
                    request_deserializer=fishing__pb2.InventoryRequest.FromString,
                    response_serializer=fishing__pb2.InventoryResponse.SerializeToString,
            ),
            'GetImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImage,
                    request_deserializer=fishing__pb2.ImageRequest.FromString,
                    response_serializer=fishing__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fishingapp.FishingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fishingapp.FishingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FishingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fishingapp.FishingService/ListUsers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            fishing__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fishingapp.FishingService/Login',
            fishing__pb2.LoginRequest.SerializeToString,
            fishing__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLocation(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/fishingapp.FishingService/UpdateLocation',
            fishing__pb2.UpdateLocationRequest.SerializeToString,
            fishing__pb2.UpdateLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartFishing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fishingapp.FishingService/StartFishing',
            fishing__pb2.StartFishingRequest.SerializeToString,
            fishing__pb2.Fish.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CurrentUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fishingapp.FishingService/CurrentUsers',
            fishing__pb2.EmptyRequest.SerializeToString,
            fishing__pb2.CurrentUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Inventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fishingapp.FishingService/Inventory',
            fishing__pb2.InventoryRequest.SerializeToString,
            fishing__pb2.InventoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fishingapp.FishingService/GetImage',
            fishing__pb2.ImageRequest.SerializeToString,
            fishing__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
