# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fishing.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fishing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfishing.proto\x12\nfishingapp\x1a\x1bgoogle/protobuf/empty.proto\"<\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\x12\n\nis_fishing\x18\x04 \x01(\x08\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\":\n\x15UpdateLocationRequest\x12\x0b\n\x03jwt\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\")\n\x16UpdateLocationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\"\n\x13StartFishingRequest\x12\x0b\n\x03jwt\x18\x01 \x01(\t\"=\n\x04\x46ish\x12\x0f\n\x07\x66ish_id\x18\x01 \x01(\x05\x12\x10\n\x08\x66ish_dna\x18\x02 \x01(\t\x12\x12\n\nfish_level\x18\x03 \x01(\x05\"\x0e\n\x0c\x45mptyRequest\"%\n\x14\x43urrentUsersResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"\x12\n\x10InventoryRequest\"3\n\x11InventoryResponse\x12\x1e\n\x04\x66ish\x18\x01 \x03(\x0b\x32\x10.fishingapp.Fish\"\x0e\n\x0cImageRequest\"#\n\rImageResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x32\x80\x04\n\x0e\x46ishingService\x12\x37\n\tListUsers\x12\x16.google.protobuf.Empty\x1a\x10.fishingapp.User0\x01\x12<\n\x05Login\x12\x18.fishingapp.LoginRequest\x1a\x19.fishingapp.LoginResponse\x12Y\n\x0eUpdateLocation\x12!.fishingapp.UpdateLocationRequest\x1a\".fishingapp.UpdateLocationResponse(\x01\x12\x43\n\x0cStartFishing\x12\x1f.fishingapp.StartFishingRequest\x1a\x10.fishingapp.Fish0\x01\x12L\n\x0c\x43urrentUsers\x12\x18.fishingapp.EmptyRequest\x1a .fishingapp.CurrentUsersResponse0\x01\x12H\n\tInventory\x12\x1c.fishingapp.InventoryRequest\x1a\x1d.fishingapp.InventoryResponse\x12?\n\x08GetImage\x12\x18.fishingapp.ImageRequest\x1a\x19.fishingapp.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fishing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=58
  _globals['_USER']._serialized_end=118
  _globals['_LOGINREQUEST']._serialized_start=120
  _globals['_LOGINREQUEST']._serialized_end=170
  _globals['_LOGINRESPONSE']._serialized_start=172
  _globals['_LOGINRESPONSE']._serialized_end=202
  _globals['_UPDATELOCATIONREQUEST']._serialized_start=204
  _globals['_UPDATELOCATIONREQUEST']._serialized_end=262
  _globals['_UPDATELOCATIONRESPONSE']._serialized_start=264
  _globals['_UPDATELOCATIONRESPONSE']._serialized_end=305
  _globals['_STARTFISHINGREQUEST']._serialized_start=307
  _globals['_STARTFISHINGREQUEST']._serialized_end=341
  _globals['_FISH']._serialized_start=343
  _globals['_FISH']._serialized_end=404
  _globals['_EMPTYREQUEST']._serialized_start=406
  _globals['_EMPTYREQUEST']._serialized_end=420
  _globals['_CURRENTUSERSRESPONSE']._serialized_start=422
  _globals['_CURRENTUSERSRESPONSE']._serialized_end=459
  _globals['_INVENTORYREQUEST']._serialized_start=461
  _globals['_INVENTORYREQUEST']._serialized_end=479
  _globals['_INVENTORYRESPONSE']._serialized_start=481
  _globals['_INVENTORYRESPONSE']._serialized_end=532
  _globals['_IMAGEREQUEST']._serialized_start=534
  _globals['_IMAGEREQUEST']._serialized_end=548
  _globals['_IMAGERESPONSE']._serialized_start=550
  _globals['_IMAGERESPONSE']._serialized_end=585
  _globals['_FISHINGSERVICE']._serialized_start=588
  _globals['_FISHINGSERVICE']._serialized_end=1100
# @@protoc_insertion_point(module_scope)
