# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fishing_pb2 as fishing__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FishingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_stream(
                '/fishingapp.FishingService/ListUsers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=fishing__pb2.User.FromString,
                )
        self.Login = channel.unary_unary(
                '/fishingapp.FishingService/Login',
                request_serializer=fishing__pb2.LoginRequest.SerializeToString,
                response_deserializer=fishing__pb2.LoginResponse.FromString,
                )
        self.UpdateLocation = channel.stream_unary(
                '/fishingapp.FishingService/UpdateLocation',
                request_serializer=fishing__pb2.UpdateLocationRequest.SerializeToString,
                response_deserializer=fishing__pb2.UpdateLocationResponse.FromString,
                )
        self.StartFishing = channel.unary_stream(
                '/fishingapp.FishingService/StartFishing',
                request_serializer=fishing__pb2.StartFishingRequest.SerializeToString,
                response_deserializer=fishing__pb2.Fish.FromString,
                )
        self.CurrentUsers = channel.unary_stream(
                '/fishingapp.FishingService/CurrentUsers',
                request_serializer=fishing__pb2.EmptyRequest.SerializeToString,
                response_deserializer=fishing__pb2.CurrentUsersResponse.FromString,
                )
        self.Inventory = channel.unary_unary(
                '/fishingapp.FishingService/Inventory',
                request_serializer=fishing__pb2.InventoryRequest.SerializeToString,
                response_deserializer=fishing__pb2.InventoryResponse.FromString,
                )
        self.GetImage = channel.unary_unary(
                '/fishingapp.FishingService/GetImage',
                request_serializer=fishing__pb2.ImageRequest.SerializeToString,
                response_deserializer=fishing__pb2.ImageResponse.FromString,
                )


class FishingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLocation(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartFishing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CurrentUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inventory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FishingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUsers': grpc.unary_stream_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=fishing__pb2.User.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=fishing__pb2.LoginRequest.FromString,
                    response_serializer=fishing__pb2.LoginResponse.SerializeToString,
            ),
            'UpdateLocation': grpc.stream_unary_rpc_method_handler(
                    servicer.UpdateLocation,
                    request_deserializer=fishing__pb2.UpdateLocationRequest.FromString,
                    response_serializer=fishing__pb2.UpdateLocationResponse.SerializeToString,
            ),
            'StartFishing': grpc.unary_stream_rpc_method_handler(
                    servicer.StartFishing,
                    request_deserializer=fishing__pb2.StartFishingRequest.FromString,
                    response_serializer=fishing__pb2.Fish.SerializeToString,
            ),
            'CurrentUsers': grpc.unary_stream_rpc_method_handler(
                    servicer.CurrentUsers,
                    request_deserializer=fishing__pb2.EmptyRequest.FromString,
                    response_serializer=fishing__pb2.CurrentUsersResponse.SerializeToString,
            ),
            'Inventory': grpc.unary_unary_rpc_method_handler(
                    servicer.Inventory,
                    request_deserializer=fishing__pb2.InventoryRequest.FromString,
                    response_serializer=fishing__pb2.InventoryResponse.SerializeToString,
            ),
            'GetImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImage,
                    request_deserializer=fishing__pb2.ImageRequest.FromString,
                    response_serializer=fishing__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fishingapp.FishingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FishingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/fishingapp.FishingService/ListUsers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            fishing__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fishingapp.FishingService/Login',
            fishing__pb2.LoginRequest.SerializeToString,
            fishing__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateLocation(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/fishingapp.FishingService/UpdateLocation',
            fishing__pb2.UpdateLocationRequest.SerializeToString,
            fishing__pb2.UpdateLocationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartFishing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/fishingapp.FishingService/StartFishing',
            fishing__pb2.StartFishingRequest.SerializeToString,
            fishing__pb2.Fish.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CurrentUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/fishingapp.FishingService/CurrentUsers',
            fishing__pb2.EmptyRequest.SerializeToString,
            fishing__pb2.CurrentUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Inventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fishingapp.FishingService/Inventory',
            fishing__pb2.InventoryRequest.SerializeToString,
            fishing__pb2.InventoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fishingapp.FishingService/GetImage',
            fishing__pb2.ImageRequest.SerializeToString,
            fishing__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class VotingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prepare = channel.unary_unary(
                '/fishingapp.VotingService/Prepare',
                request_serializer=fishing__pb2.VoteRequest.SerializeToString,
                response_deserializer=fishing__pb2.VoteResponse.FromString,
                )
        self.CommitTransaction = channel.unary_unary(
                '/fishingapp.VotingService/CommitTransaction',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class VotingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Prepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VotingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=fishing__pb2.VoteRequest.FromString,
                    response_serializer=fishing__pb2.VoteResponse.SerializeToString,
            ),
            'CommitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitTransaction,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fishingapp.VotingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VotingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fishingapp.VotingService/Prepare',
            fishing__pb2.VoteRequest.SerializeToString,
            fishing__pb2.VoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fishingapp.VotingService/CommitTransaction',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DecisionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GlobalDecision = channel.unary_unary(
                '/fishingapp.DecisionService/GlobalDecision',
                request_serializer=fishing__pb2.GlobalDecisionRequest.SerializeToString,
                response_deserializer=fishing__pb2.GlobalDecisionResponse.FromString,
                )
        self.InternalPrepare = channel.unary_unary(
                '/fishingapp.DecisionService/InternalPrepare',
                request_serializer=fishing__pb2.InternalPrepareRequest.SerializeToString,
                response_deserializer=fishing__pb2.InternalPrepareResponse.FromString,
                )
        self.InternalDecision = channel.unary_unary(
                '/fishingapp.DecisionService/InternalDecision',
                request_serializer=fishing__pb2.InternalDecisionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class DecisionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GlobalDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InternalPrepare(self, request, context):
        """Internal RPC for internal communication between phases on same node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InternalDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GlobalDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalDecision,
                    request_deserializer=fishing__pb2.GlobalDecisionRequest.FromString,
                    response_serializer=fishing__pb2.GlobalDecisionResponse.SerializeToString,
            ),
            'InternalPrepare': grpc.unary_unary_rpc_method_handler(
                    servicer.InternalPrepare,
                    request_deserializer=fishing__pb2.InternalPrepareRequest.FromString,
                    response_serializer=fishing__pb2.InternalPrepareResponse.SerializeToString,
            ),
            'InternalDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.InternalDecision,
                    request_deserializer=fishing__pb2.InternalDecisionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fishingapp.DecisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DecisionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GlobalDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fishingapp.DecisionService/GlobalDecision',
            fishing__pb2.GlobalDecisionRequest.SerializeToString,
            fishing__pb2.GlobalDecisionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InternalPrepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fishingapp.DecisionService/InternalPrepare',
            fishing__pb2.InternalPrepareRequest.SerializeToString,
            fishing__pb2.InternalPrepareResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InternalDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fishingapp.DecisionService/InternalDecision',
            fishing__pb2.InternalDecisionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
